### ISSUE TITLE
CAD files?

### ISSUE THREAD

**Issue by b-morgan** [KeepThisTicket/weatherClock#1]
The link in the README.md for the CAD files only points to one file. I was expecting more than one file.

**Comment by DonRohan** [comment]
The file points to both required shapes, sadly it is read-only (at least for me and a friend of mine)

**Comment by KeepThisTicket** [comment]
Yes, sorry for a while one part was hidden (it is 2 parts total - a top and bottom part). You had to click the eye icon in the bottom left to make it visible. Now both parts should be visible and yes - like @DonRohan mentioned, just right click the part you want and then export. You can also right click the name of the part in the bottom left as well.
