### ISSUE TITLE
icon logic // sun/moon-dichotomy

### ISSUE THREAD

**Issue by 0x0lli** [KeepThisTicket/weatherClock#10]
@KeepThisTicket 
I still haven't understood what logic stands behind the choice of icon. Would you be so kind to elaborate on that?

In the current release status, there is no differentiation between the sun/moon. I highly appreciate the merge you made yesterday, it does good for the optical representation of the text, thank you.
However, I am shown sun for 3am/4am now, which is logically impossible for where I live, which is Frankfurt/Germany. Sunset is somewhere around 8AM.
I would love to help optimize the logic behind it.

**Comment by KeepThisTicket** [comment]
Yes - this would be really nice to have ! The way openWeather does icons is that it uses the sun image icon set during the day, and then the moon icon image set during the night. I never implemented the daytime/nighttime logic to check and change the icon set, but this would be an enhancement for sure ! 

So the reason you see "sun" at night, it just means clear skies - in this enhancement with the sun/moon icon set, at night you would see a moon for clear skies.

**Comment by 0x0lli** [comment]
[alternative_icon_pack.zip](https://github.com/KeepThisTicket/weatherClock/files/7229510/alternative_icon_pack.zip)
This is an alternative icon package that could replace the orignal one, I would love to have @plotn integrate it on a boolean-switch-basis. I grabbed it from:
https://www.behance.net/gallery/2235034/Animated-weather-icons
, contacted the owner and he was fine with its use here. I edited it very little in order to have it fit to the resolution and still preserve the info as the original ones were high-resolution. So everything nice looking is due to the skills of the author, everything ugly my fault. (have little coding-, even less graphical skills over here, sorry)

due to time constraints, I will not be able to look into the icon-display-logic within the upcoming three weeks but surely will, thereafter as the project really has a lot of my sympathy but I am more of a debugger user than a programmer and need exponentially more time to finish code than experienced programmers. If anyone is able to until then, those appear to be a good start:
https://openweathermap.org/weather-conditions
https://github.com/lcpz/lain/issues/370

**Comment by plotn** [comment]
Hi! 
Why dont you integrate it yourself?
I think it is trivial task...

**Comment by 0x0lli** [comment]
I have little experience coding and of course, will try to do so after my exams are over, which is mid-October.
Also, would love to establish a multiple location switch. sorry if you got me wrong, was just thinking loud. :)

**Comment by plotn** [comment]
No no, all okay) Continue to think aloud - the evolution of the project - it is always good.

Maybe I'll implement your icons this week, I think it is 30m - 2h work.

Another one thing - you asked about icons and its logic. Could you re-check - is everything okay? I think you should find out openweathermap api and analyze values in code (try to find numbers 801,802 etc and you will find logic of these ranges.

**Comment by plotn** [comment]
I was wrong - it took 10minutes :)
You can get the latest version with two themes (theme name is the name of a folder with icons)

**Comment by 0x0lli** [comment]
> No no, all okay) Continue to think aloud - the evolution of the project - it is always good.
> 
> Maybe I'll implement your icons this week, I think it is 30m - 2h work.
> 
> Another one thing - you asked about icons and its logic. Could you re-check - is everything okay? I think you should find out openweathermap api and analyze values in code (try to find numbers 801,802 etc and you will find logic of these ranges.

I reckon it will not be OK unless a feature to check coordinates' related sunrise- and sunset-times will be integrated and the icons chosen according to that logic. I have not edited the icons according to that yet but aim to. Right now, the icons are basically just analogs of the official openweathermap icons.

**Comment by pjockey** [comment]
Where does this project stand  as to using git to pull and update?

**Comment by plotn** [comment]
https://youtu.be/IV6CFZ7b_24

**Comment by pjockey** [comment]
> https://youtu.be/IV6CFZ7b_24

???

**Comment by plotn** [comment]
I did not understand you wrote, so i decided to joke. Please say in another words.

**Comment by pjockey** [comment]
OH, OK, sorry.

Has Github repo for this project been updated? Or is there a fork that can be used  to update my Weather-Clock, the one I'm using?

I was just wondering if the OP had updated the repo so One could use `git pull` to get the latest and greatest script and icons?

**Comment by plotn** [comment]
You can download my fork of this repo - it is updated yesterday. When (and if) my pull request will be applied to this repo - you'll be able to take from here - everything as usual.

**Comment by KeepThisTicket** [comment]
Closing this issue as it was added with the merge of PR #9. Thanks @plotn !
