### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Naglafarn** [KeepThisTicket/weatherClock#11]
I am not at all good at coding, but i changed the standard values to be German incl. displaying the days and values in German.

 Had to insert these values:
```
from datetime import datetime, timedelta
import locale
# Umstellung auf Deutsch:
locale.setlocale(locale.LC_ALL, 'de_DE.utf8')
```

and made these changes too:
`       weatherText.goto(weatherText_Description, weatherText_vertSpacing*3)
        weatherText.color("white")
        # day of the week
        weatherText.write("Tag", align="right", font=("Verdana", weatherText_DescriptionFontSize, "bold"))

        weatherText.goto(weatherText_Data, weatherText_vertSpacing*3)
        if not tomorrow_date:
            weatherText.write(datetime.today().strftime('%A'),
                              align="left", font=("Verdana", weatherText_DataFontSize, "bold"))
        else:
            weatherText.write(tomorrow_date.strftime('%A'),
                              align="left", font=("Verdana", weatherText_DataFontSize, "bold"))

        # hour of the day
        weatherText.goto(weatherText_Description, weatherText_vertSpacing*2)
        weatherText.write("Uhrzeit", align="right", font=("Verdana", weatherText_DescriptionFontSize, "bold"))

        weatherText.goto(weatherText_Data, weatherText_vertSpacing*2)
        weatherText.write(str(hour_touched) + " " + touched_meridiem,
                          align="left", font=("Verdana", weatherText_DataFontSize, "bold"))

        # temperature
        weatherText.goto(weatherText_Description, weatherText_vertSpacing)
        weatherText.write("Temperatur", align="right", font=("Verdana", weatherText_DescriptionFontSize, "bold"))

        weatherText.goto(weatherText_Data, weatherText_vertSpacing)
        weatherText.write(str(round_half_up(data["hourly"][hours_ahead]["temp"], 1)) + degree_sign,
                          align="left", font=("Verdana", weatherText_DataFontSize, "bold"))

        # Feels like
        weatherText.goto(weatherText_Description, 0)
        weatherText.write("Gefuehlt", align="right",
                          font=("Verdana", weatherText_DescriptionFontSize, "bold"))

        weatherText.goto(weatherText_Data, 0)
        weatherText.write(str(round_half_up(data["hourly"][hours_ahead]["feels_like"], 1)) + degree_sign,
                          align="left", font=("Verdana", weatherText_DataFontSize, "bold"))

        # POP
        weatherText.goto(weatherText_Description, -weatherText_vertSpacing)
        weatherText.write("Regenchance", align="right", font=("Verdana", weatherText_DescriptionFontSize, "bold"))

        weatherText.goto(weatherText_Data, -weatherText_vertSpacing)
        weatherText.write(str(int(data["hourly"][hours_ahead]["pop"]*100)) + " %",
                          align="left", font=("Verdana", weatherText_DataFontSize, "bold"))

        # Rain
        weatherText.goto(weatherText_Description, -weatherText_vertSpacing*2)
        weatherText.write("Regenmenge", align="right", font=("Verdana", weatherText_DescriptionFontSize, "bold"))

        weatherText.goto(weatherText_Data, -weatherText_vertSpacing*2)
        if 'rain' not in data["hourly"][hours_ahead]:
            weatherText.write("--", align="left", font=("Verdana", weatherText_DataFontSize, "bold"))
        else:
            weatherText.write(str(data["hourly"][hours_ahead]["rain"]["1h"]) + " mm",
                              align="left", font=("Verdana", weatherText_DataFontSize, "bold"))

        # Wind
        weatherText.goto(weatherText_Description, -weatherText_vertSpacing*3)
        weatherText.write("Wind", align="right", font=("Verdana", weatherText_DescriptionFontSize, "bold"))

[weatherClock-German.zip](https://github.com/KeepThisTicket/weatherClock/files/7296120/weatherClock-German.zip)
`

**Comment by vierlijner** [comment]
> Anyone can help me how to display 24:00 hour values vs 12:00?

currentHour24 = int(time.strftime("%H"))
currentHour12 = int(time.strftime("%I"))

Only you have to make some changes for the count hoursAhead, because it's easier because you don't have to know if it's AM or PM. but >23 = next day.

I also thought to make this dynamic, so to check your timezone and the display it like 12 of 24 hours. But maybe a setting is easier and the it does this automatic.
