### ISSUE TITLE
24hours time format

### ISSUE THREAD

**Issue by Sebwap** [KeepThisTicket/weatherClock#7]
Hello, Not sure, but I think that "24 hours format management" is not done.

Am I correct ?

For example, it's 3PM (15H) here and if i click on 4 hours on the screen, I got weather for tomorrow 4AM instead of today 4PM (16H)

**Comment by pjockey** [comment]
> Hello, Not sure, but I think that "24 hours format management" is not done.
> 
> Am I correct ?
> 
> For example, it's 3PM (15H) here and if i click on 4 hours on the screen, I got weather for tomorrow 4AM instead of today 4PM (16H)

Yes there is a problem as I have this issue as well.

**Comment by skibum-za** [comment]
+1

**Comment by KeepThisTicket** [comment]
I have gotten emails about this issue as well. Will update here once issue is fixed (believe others are working on it in some of the PRs)

**Comment by Vacant0mens** [comment]
I've fixed this issue in the [last commit to my PR](https://github.com/Vacant0mens/weatherClock/commit/3cdf944dc6917ffbe2d34abd8a8b082337577978)

**Comment by pjockey** [comment]
When will these PR's make it into the Master?

**Comment by Sebwap** [comment]
Thanks for taking this into consideration for 24h format lover =)

**Comment by KeepThisTicket** [comment]
Tested and merged with PR#8. Thanks to work by @Vacant0mens !
